MAIL_SERVICE_PORT: 9021

# Internal Docker DNS name of Mailcow Postfix service.
# Do not use the public domain here.
MAIL_SERVICE_DOMAIN: postfix-mailcow

DEFAULT_MAX_BODY_SIZE: 50M
DEFAULT_PROXY_CONNECT_TIMEOUT: 200s
DEFAULT_PROXY_SEND_TIMEOUT: 200s
DEFAULT_PROXY_READ_TIMEOUT: 200s

MAIL_SERVICE_IMAGE: ghcr.io/morphyxis/mail-service
MAIL_SERVICE_VERSION: 1.1.10