---
- name: mail-service nginx config
  become: true
  tasks:
    - name: Render nginx config
      template:
        src: mail-service.conf.j2
        dest: /etc/nginx/sites-enabled/mail-service.conf
